### ISSUE TITLE
A quick getting started guide in the readme would be much appreciated

### ISSUE THREAD

**Issue by david-pfx** [zalo/libfive-unity#3]
I guess the idea is to clone the repo into a Unity project.

Nothing could possibly go wrong.

**Comment by zalo** [comment]
The repo stands as an independent Unity Project, but you can incorporate it into an existing project by dragging the `libfive` folder in `Assets` into the `Assets` folder of the existing project (while Unity is turned off, of course).

As for how to use it... I haven't had time to write documentation 🙃 

Hopefully, the structure of the example scene is something close to self-explanatory...
